src/Entity/Job.php
<?php

namespace App\Entity;

use Doctrine\Common\Collections\ArrayCollection;
use Doctrine\Common\Collections\Collection;
use Doctrine\ORM\Mapping as ORM;

/**
 * @ORM\Entity(repositoryClass="App\Repository\JobRepository")
 */
class Job
{
    /**
     * @ORM\Id()
     * @ORM\GeneratedValue()
     * @ORM\Column(type="integer")
     */
    private $id;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $title;

    /**
     * @ORM\Column(type="text")
     */
    private $description;

    /**
     * @ORM\Column(type="string", length=255)
     */
    private $code;


    /**
     * @ORM\Column(type="datetime")
     */
    private $create_at;

    /**
     * @ORM\ManyToOne(targetEntity="App\Entity\City")
     */
    private $city;

 /**
     * @ORM\ManyToOne(targetEntity="App\Entity\Statut")
     */
    private $statut;
    
    public function __construct()
    {
        $this->code = uniqid();
        $this->create_at = new \DateTime();
    }

    public function getId(): ?int
    {
        return $this->id;
    }

    public function getTitle(): ?string
    {
        return $this->title;
    }

    public function setTitle(string $title): self
    {
        $this->title = $title;

        return $this;
    }

    public function getDescription(): ?string
    {
        return $this->description;
    }

    public function setDescription(string $description): self
    {
        $this->description = $description;

        return $this;
    }

    public function getCode(): ?string
    {
        return $this->code;
    }

    public function setCode(string $code): self
    {
        $this->code = $code;

        return $this;
    }   

    public function getCreateAt(): ?\DateTimeInterface
    {
        return $this->create_at;
    }

    public function setCreateAt(\DateTimeInterface $create_at): self
    {
        $this->create_at = $create_at;

        return $this;
    }

    public function getCity(): ?City
    {
        return $this->city;
    }

    public function setCity(?City $city): self
    {
        $this->city = $city;

        return $this;
    }

    public function getStatut(): ?Statut
    {
        return $this->statut;
    }

    public function setStatut(?Statut $statut): self
    {
        $this->statut = $statut;

        return $this;
    }
}

src/Form/frontoffice/AppFront.php
<?php

namespace App\Form\frontoffice;

use App\Entity\Application;
use App\Entity\Job;
use Symfony\Component\Form\AbstractType;
use Symfony\Component\Form\FormBuilderInterface;
use Symfony\Component\OptionsResolver\OptionsResolver;
use Symfony\Component\Form\Extension\Core\Type\SubmitType;
use Symfony\Component\Form\Extension\Core\Type\FileType;
use Symfony\Bridge\Doctrine\Form\Type\EntityType;

class AppFront extends AbstractType
{
    public function buildForm(FormBuilderInterface $builder, array $options)
    {
        $builder
            ->add('firstName')
            ->add('lastName')
            ->add('address')
            ->add('email')
            ->add('phone')
           ->add('cv', FileType::class,array('label' => 'Ajouter votre CV'))
            ->add('submit', SubmitType::class, array('label' => 'Postuler'));
    }

    public function configureOptions(OptionsResolver $resolver)
    {
        $resolver->setDefaults([
            'data_class' => Application::class,
        ]);
    }
}

templates/frontoffice/base.html.twig
<!DOCTYPE html>
<html>
    <head>
        <meta charset="UTF-8">
        
        <title>{% block title %}List job!{% endblock %}</title>
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css">
     {% block stylesheets %}
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
        {% endblock %}
    </head>
    <body style="background-color: rgb(223, 240, 235) ">
        {% block body %}{% endblock %}
        {% block javascripts %}
        <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
        <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>{% endblock %}
    </body>
</html>

templates/frontoffice/detail_job.html.twig
{% extends '/frontoffice/base.html.twig' %}
{% block title %}Job's detail{% endblock %}
{% form_theme form 'bootstrap_4_layout.html.twig' %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><span style="color:rgb(245, 157, 42) " >emplois</span> <span style="color:rgb(22, 211, 224)" >informatique</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div style="margin-left: 40%">
          <ul class="navbar-nav mr-auto">
              
            <li class="nav-item">
              <a class="nav-link" href="{{path('home')}}" style="font-size: 20px">Home</a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{path('jobs_index')}}" style="margin-left:50px;font-size: 20px" >Offres</a>
            </li>
           
          
          </ul>
        </div>
        
        </div>
      </nav>
      <div class="container" style="background: whitesmoke;border-radius: 10px;margin-top: 50px" >

          <div class="row"> 
           
            <div class="col-xs-12 col-sm-8 col-lg-8" style="background-color:whitesmoke;border-radius: 20px;padding-right:100px">
            
 

<div class="card" style="margin-left: 30px;margin-top: 100px"  >
    
        <div class="card-body" style="background-color:rgb(220, 229, 230);height: 400px">
          <blockquote class="blockquote mb-0">
                <h2 class="card-title;" ><center>{{ job.title }}</center></h2>
                <hr>
            <p>Vous souhaitez rejoindre une équipe dynamique, vous avez envie d'évoluer dans une structure jeune, 
              si vous avez des conaissances sur :<br>
              {{ job.description }} <br>
              Alors postuler à ce poste maintenant !!<br><br></p>
              <div class="row">
                  <ul>
                      
                      <li> <strong>Ville</strong> : {{job.city.name}}<br></li>
                      <li><strong>Publier le</strong>  : {{ job.createAt|date('d-m-Y') }}</li>
              </ul>
              <ul style="margin-left: 50px">
                  <li> <strong>Code</strong> : {{job.code}}</li>
              </ul>
            </div>
          </blockquote>
        </div>
      </div>

  </div>
      
      <div class="col-xs-12 col-sm-4 col-lg-4" style="background-color: rgb(179, 233, 236);border-radius: 20px; ">
       
      <div class="container" style="margin-right: 1px;margin-left: 1px" >
        <div class="row mt-4">
          <div class="row col-md-6 mx-auto">
            <div class="card  rounded" style="background-color: rgb(179, 233, 236);margin-left: -100px;margin-right: -100px;margin-top: -10px;margin-bottom: 10px;">
              <div class="container-fluid">
                <h3 class="card-title text-default p-4"> <center>Le formulaire</center> </h3>
                <div class="card-body mt-2 rounded">
                  {{form(form)}}
                </div>
              </div>
            </div>
          </div>
        </div>
      </div>
    </div>
    </div>
    </div>
    <br>  <br>  <br>
    <br>  <br>  <br>
    
    <footer style="background-color: rgb(33, 40, 56); height: 300px; width:100%;border-top-left-radius: 8px;border-top-right-radius: 8px;" >
     
        <div class="row">
           
           <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;">
              <h5 class="foooter__title" style="color: whitesmoke;padding-left: 40px;padding-top: 40px;">Entreprises(SSII)</h5>
              <ul>
                <li><a href="https://www.ibm.com"><span style="color:rgb(211, 206, 206)">IBM</span></a></li>
                <li><a href="https://www.atos.net/fr" ><span style="color:rgb(211, 206, 206)">Atos</span></a></li>
                <li><a href="https://www.sqli.com/authors" ><span style="color:rgb(211, 206, 206)">SQLI</span></a></li>
                <li><a href="https://www.mobiblanc.com" ><span style="color:rgb(211, 206, 206)">MobiBlanc</span></a></li>
              
            
              </ul>
            </div>
            <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;;padding-left: 50px">
                <p class="foooter__title" style="color: whitesmoke;padding-top: 60px;"></p>
                <ul>
                  <li><a  href="https://www.capgemini.com"><span style="color:rgb(211, 206, 206)">Capgimini</span></a></li>
                  <li><a  href="https://www.idmaj.ma"><span style="color:rgb(211, 206, 206)">Technologie</span> </a></li>
                  <li><a  href="https://www.mattelicom.com"><span style="color:rgb(211, 206, 206)">Mattelicom</span></a></li>
                  <li><a  href="https://www.oriensys.ma"><span style="color:rgb(211, 206, 206)">Oriensys Service</span></a></li>
      
      
              
                </ul>
              </div>
              <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;;padding-left: 50px">
                  <p class="foooter__title" style="color: whitesmoke;padding-top: 60px;"></p>
                  <ul>
                    <li><a  href="https://www.admiral.ma"><span style="color:rgb(211, 206, 206)">Admiral</span></a></li>
                    <li><a  href="https://www.collabsys.ma"><span style="color:rgb(211, 206, 206)">Collabsys</span></a></li>
                    <li><a  href="https://www.webin.ma"><span style="color:rgb(211, 206, 206)">Webin</span ></a></li>
                    <li><a  href="https://www.benkdigital.com"><span style="color:rgb(211, 206, 206)">Benkdigital</span></a></li>
        
        
                
                  </ul>
                </div>
          
         
          </div>
          <br><br>
            <div  style="color: rgb(226, 225, 225);background-color: rgb(33, 40, 56);margin-top: 40px">
              &copy;
              <script>
                document.write(new Date().getFullYear())
              </script>, Created by Hajar EL-HAMIDY <strong>(ENSET-M GLSID)</strong>
             
            </div>
         
        </footer>
{% endblock %}

templates/frontoffice/display_job.html.twig
{% extends '/frontoffice/base.html.twig' %}
{% block title %}List for Jobs{% endblock %}

{% block body %}
<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#"><span style="color:rgb(245, 157, 42) " >emplois</span> <span style="color:rgb(22, 211, 224)" >informatique</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div style="margin-left: 40%">
          <ul class="navbar-nav mr-auto">
              
            <li class="nav-item ">
              <a class="nav-link" href="{{path('home')}}" style="font-size: 20px">Home </a>
            </li>
            <li class="nav-item active">
              <a class="nav-link" href="{{path('jobs_index')}}" style="margin-left:50px;font-size: 20px" >Offres <span class="sr-only" >(current)</span></a>
            </li>
           
          
          </ul>
        </div>
        
        </div>
      </nav>
  <br>
  <div class="container"style="margin: 100px">


      {% for job in jobs %}
      {% if job.statut.id==2 %}
      <div style="margin-left: 200px;margin-right: 200px; margin-bottom:30px">
       <div class="card text-center" >
          <div class="card-header" style="background-color: rgb(22, 211, 224)">
         
          </div>
          <div class="card-body">
            <h5 class="card-title"><span style='color: rgb(57, 67, 90); '><i>Titre :    {{job.title}} ,   N° de l'offre est  :  {{job.id}}</i></span> </h5>
            <p class="card-text">{{ job.description }}</p>
           <center><a href="{{ path('detail_job',{id:job.id})}}" class="btn btn-primary ">Lire la suite</a></center> 
          </div>
          
        </div>
      </div>
      {% endif %}

        {% endfor %}

      </div>
      
          <footer style="background-color: rgb(33, 40, 56); height: 300px; width:100%;border-top-left-radius: 8px;border-top-right-radius: 8px;" >
     
        <div class="row">
           
           <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;">
              <h5 class="foooter__title" style="color: whitesmoke;padding-left: 40px;padding-top: 40px;">Entreprises(SSII)</h5>
              <ul>
                <li><a href="https://www.ibm.com"><span style="color:rgb(211, 206, 206)">IBM</span></a></li>
                <li><a href="https://www.atos.net/fr" ><span style="color:rgb(211, 206, 206)">Atos</span></a></li>
                <li><a href="https://www.sqli.com/authors" ><span style="color:rgb(211, 206, 206)">SQLI</span></a></li>
                <li><a href="https://www.mobiblanc.com" ><span style="color:rgb(211, 206, 206)">MobiBlanc</span></a></li>
              
            
              </ul>
            </div>
            <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;;padding-left: 50px">
                <p class="foooter__title" style="color: whitesmoke;padding-top: 60px;"></p>
                <ul>
                  <li><a  href="https://www.capgemini.com"><span style="color:rgb(211, 206, 206)">Capgimini</span></a></li>
                  <li><a  href="https://www.idmaj.ma"><span style="color:rgb(211, 206, 206)">Technologie</span> </a></li>
                  <li><a  href="https://www.mattelicom.com"><span style="color:rgb(211, 206, 206)">Mattelicom</span></a></li>
                  <li><a  href="https://www.oriensys.ma"><span style="color:rgb(211, 206, 206)">Oriensys Service</span></a></li>
      
      
              
                </ul>
              </div>
              <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;;padding-left: 50px">
                  <p class="foooter__title" style="color: whitesmoke;padding-top: 60px;"></p>
                  <ul>
                    <li><a  href="https://www.admiral.ma"><span style="color:rgb(211, 206, 206)">Admiral</span></a></li>
                    <li><a  href="https://www.collabsys.ma"><span style="color:rgb(211, 206, 206)">Collabsys</span></a></li>
                    <li><a  href="https://www.webin.ma"><span style="color:rgb(211, 206, 206)">Webin</span ></a></li>
                    <li><a  href="https://www.benkdigital.com"><span style="color:rgb(211, 206, 206)">Benkdigital</span></a></li>
        
        
                
                  </ul>
                </div>
          
         
          </div>
          <br><br>
            <div  style="color: rgb(226, 225, 225);background-color: rgb(33, 40, 56);margin-top: 40px">
              &copy;
              <script>
                document.write(new Date().getFullYear())
              </script>, Created by Hajar EL-HAMIDY <strong>(ENSET-M GLSID)</strong>
             
            </div>
         
        </footer>

  {% endblock %}

templates/frontoffice/home.html.twig
{% extends '/frontoffice/base.html.twig' %}
{% block title %}Home page{% endblock %}

{% block body %}

<nav class="navbar navbar-expand-lg navbar-light bg-light">
    <a class="navbar-brand" href="#" style="font-size: 20px"><span style="color:rgb(245, 157, 42) " >emplois</span> <span style="color:rgb(22, 211, 224)" >informatique</span></a>
    <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
      <span class="navbar-toggler-icon"></span>
    </button>
       
        <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
      
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <div style="margin-left: 40%">
          <ul class="navbar-nav mr-auto">
              
            <li class="nav-item active">
              <a class="nav-link" href="{{path('home')}}" style="font-size: 20px">Home <span class="sr-only" >(current)</span></a>
            </li>
            <li class="nav-item">
              <a class="nav-link" href="{{path('jobs_index')}}" style="margin-left:50px;font-size: 20px" >Offres</a>
            </li>
           
          
          </ul>
        </div>
        
        </div>
      </nav>
          <div id="carouselExampleIndicators" class="carousel slide" data-ride="carousel">
            <ol class="carousel-indicators">
              <li data-target="#carouselExampleIndicators" data-slide-to="0" class="active"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="1"></li>
              <li data-target="#carouselExampleIndicators" data-slide-to="2"></li>
            </ol>
            <div class="carousel-inner">
              <div class="carousel-item active">
                  <img src="{{ asset('assets/p2.jpg')}}" class="d-block w-100" alt="1" style="width: 100%; height: 450px;"/>
              </div>
              <div class="carousel-item">
                  <img src="{{ asset('assets/2.jpg')}}" class="d-block w-100" alt="1" style="width: 100%; height: 450px;"/>
              </div>
              <div class="carousel-item">
                  <img src="{{ asset('assets/1.jpg')}}" class="d-block w-100" alt="1" style="width: 100%; height: 450px;"/>
              </div>
            </div>
            <a class="carousel-control-prev" href="#carouselExampleIndicators" role="button" data-slide="prev">
              <span class="carousel-control-prev-icon" aria-hidden="true"></span>
              <span class="sr-only">Previous</span>
            </a>
            <a class="carousel-control-next" href="#carouselExampleIndicators" role="button" data-slide="next">
              <span class="carousel-control-next-icon" aria-hidden="true"></span>
              <span class="sr-only">Next</span>
            </a>
          </div>
          
         
                  <br><br> <br>
                  
        

         
        
  <div class="container"  >

    <div class="row"> 
     
      <div class="col-xs-12 col-sm-8 col-lg-8" style="background-color:whitesmoke;border-radius: 20px; margin-left:-20px">
        <div class="cadre shdw round">
        
        <div style="margin: 30px">
          <br>
            <h2>Bienvenue !!</h2>
     <br>
     <br>
     <!-- ann-300 -->
      <p class="lead">   <span style="color:rgb(245, 157, 42) " >emplois</span> <span style="color:rgb(22, 211, 224)" >informatique</span> le site web qui dispose à tous les informaticiens
         l’opportunité de trouver  un emploi ou bien  de passer un stage,
          Notre site est l’interface entre vous et les responsables  des 
          ressources humains de toutes les sociétés de services et d’ingénierie  informatiques.<br> <br>
           A partir de <span style="color:rgb(245, 157, 42) " >emplois</span> <span style="color:rgb(22, 211, 224)" >informatique</span> vous pouvez découvrir toutes les offres  disponibles dans toutes
            les villes du Maroc.<br> <br>
            Il suffit de voir la liste des offres ensuite remplissez les formulaires des l’offres 
            d’emplois qui sont  compatibles à votre profile.<br> <br>
        Visitez <span style="color:rgb(245, 157, 42) " >emplois</span> <span style="color:rgb(22, 211, 224)" >informatique</span>  et  profitez de ses services. 
        </p>
    
  
     
      </div>
     </div></div>
      
      <div class="col-xs-12 col-sm-4 col-lg-4" style="background-color:rgb(245, 157, 42);border-radius: 20px; margin-left:20px; ">
        <div class="cadre  round">
      <div class="mm">
          <div class="container" style="margin-right: 40px;margin-top: 30px;">
              <h3>Offres les plus récents</h3> 
              <br> <br>
              {% for job in jobs %}
              
              <div class="row">
                    <div class="col-sm-12">
                    <div class="card">
                      <div class="card-body">
                        <h5 class="card-title">
                            {{ job.title }} </h5>
                        <p class="card-text">{{ job.description}}</p>
                        <a href="{{ path('detail_job',{id:job.id})}}" class="btn btn-info">Découvrire</a>
                      </div>
                    </div>
                  </div>
                </div>
                <br>
                <br>
  
      
        {% endfor %}
    
    </div>
      </div> <!-- /col droite -->
      </div>
      </div>
    </div>
    </div>
    <br><br><br>
    <br>  <br>  <br>
    <footer style="background-color: rgb(33, 40, 56); height: 300px; width:100%;border-top-left-radius: 8px;border-top-right-radius: 8px;" >
     
        <div class="row">
           
           <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;">
              <h5 class="foooter__title" style="color: whitesmoke;padding-left: 40px;padding-top: 40px;">Entreprises(SSII)</h5>
              <ul>
                <li><a href="https://www.ibm.com"><span style="color:rgb(211, 206, 206)">IBM</span></a></li>
                <li><a href="https://www.atos.net/fr" ><span style="color:rgb(211, 206, 206)">Atos</span></a></li>
                <li><a href="https://www.sqli.com/authors" ><span style="color:rgb(211, 206, 206)">SQLI</span></a></li>
                <li><a href="https://www.mobiblanc.com" ><span style="color:rgb(211, 206, 206)">MobiBlanc</span></a></li>
              
            
              </ul>
            </div>
            <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;;padding-left: 50px">
                <p class="foooter__title" style="color: whitesmoke;padding-top: 60px;"></p>
                <ul>
                  <li><a  href="https://www.capgemini.com"><span style="color:rgb(211, 206, 206)">Capgimini</span></a></li>
                  <li><a  href="https://www.idmaj.ma"><span style="color:rgb(211, 206, 206)">Technologie</span> </a></li>
                  <li><a  href="https://www.mattelicom.com"><span style="color:rgb(211, 206, 206)">Mattelicom</span></a></li>
                  <li><a  href="https://www.oriensys.ma"><span style="color:rgb(211, 206, 206)">Oriensys Service</span></a></li>
      
      
              
                </ul>
              </div>
              <div class="col__xs--6 col__sm--6 col__md--3" style="margin-left:50px;;padding-left: 50px">
                  <p class="foooter__title" style="color: whitesmoke;padding-top: 60px;"></p>
                  <ul>
                    <li><a  href="https://www.admiral.ma"><span style="color:rgb(211, 206, 206)">Admiral</span></a></li>
                    <li><a  href="https://www.collabsys.ma"><span style="color:rgb(211, 206, 206)">Collabsys</span></a></li>
                    <li><a  href="https://www.webin.ma"><span style="color:rgb(211, 206, 206)">Webin</span ></a></li>
                    <li><a  href="https://www.benkdigital.com"><span style="color:rgb(211, 206, 206)">Benkdigital</span></a></li>
        
        
                
                  </ul>
                </div>
          
         
          </div>
          <br><br>
            <div  style="color: rgb(226, 225, 225);background-color: rgb(33, 40, 56);margin-top: 40px">
              &copy;
              <script>
                document.write(new Date().getFullYear())
              </script>, Created by Hajar EL-HAMIDY <strong>(ENSET-M GLSID)</strong>
             
            </div>
         
        </footer>
  <!-- <div> <br> <br></div> -->
  {% endblock %}